x-common-variables: &common-variables
  DATABASE_URL: "postgresql+asyncpg://postgres@db/lacof"
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin"
  S3_ENDPOINT_URL: "http://minio:9000"
  S3_BUCKET_NAME: "lacof"

services:
  db:
    image: "postgres:16.4"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: "lacof"
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"

  # S3 compatible object store
  minio:
    image: "quay.io/minio/minio:RELEASE.2024-10-13T13-34-11Z"
    command: "server /data --console-address ':9001'"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      - "minio_data:/data"
    ports:
      - "9000:9000"
      - "9001:9001"

  app:
    build:
      context: "."
      target: "app"
    image: "lacof-app:latest"
    entrypoint: "uvicorn --app-dir=src --host=0.0.0.0 --reload lacof.app:application"
    environment: *common-variables
    env_file: ".env"
    volumes:
      - ".:/home/lacof/app"
    ports:
      - "8000:8000"
    depends_on:
      - "db"
      - "minio"

  dev:
    build:
      context: "."
      target: "dev"
    image: "lacof-dev:latest"
    environment: *common-variables
    env_file: ".env"
    volumes:
      - ".:/home/lacof/app"

volumes:
  minio_data:
  postgres_data:
